require: rubocop-rspec

Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Layout/LineLength:
  Max: 150
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/NestedGroups:
  Max: 5
RSpec/MessageSpies:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ContextWording:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/bundle'